[package]
name = "quick-chess"
version = "0.1.0"
authors = ["Andrew Klotz <agc.klotz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = "1.0"
